---
- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL (Python 3)
  pip:
    name: pymysql
    executable: pip3

- name: Create WordPress database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wordpress
    state: present


- name: Create WordPress user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: '{{ mysql_user }}'
    host: localhost
    password: '{{ mysql_password }}'
    priv: 'wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
    state: present

- name: Flush privileges
  command: mysql -u root -e "FLUSH PRIVILEGES;"

- name: Ensure MySQL service is started
  systemd:
    name: mysql
    state: started